default:
    image: python:3.8
    before_script:
       - apt-get update
       - apt-get install -y python3-pip
       - pip install pytest
       - pip install .
stages:
    - test
test:
    script:
        - pytest ./test/
