default:
    image: python:3.8
    before_script:
       - apt-get update
       - apt-get install -y python3-pip
       - pip install .
stages:
    - test
    - finsih
test:
    script:
        - pytest ./test/
finish:
    script:
        - echo "Pipeline finished!"
