# This workflow will install Python and sphinx, then it build the html documentation pages with sphinx and deploys it into the gh-pages branch
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build HTML Pages

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:    # Allows you to run this workflow manually from the Actions tab
    
# Set permissions for the workflow - necc. to write html-docs to gh-pages branch
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      
      # Step to checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to use the system's pre-installed Python for faster execution
      - name: Use system Python (faster)
        run: |
          echo "Using pre-installed Python: $(python --version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_sphinx.txt

      - name: Install toad-package
        run: |
          pip install -e .

      - name: Install ghp-import
        run: pip install ghp-import

      - name: Build HTML
        run: |
          cd doc/
          make toad

      - name: Run ghp-import
        run: |
            ghp-import -n -p -f -r origin -b gh-pages -d docs doc/build/html/
        